# Generated by Django 6.0 on 2026-01-01 12:55

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_meal_source_meal'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='meal',
            name='instructions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
