# Generated by Django 6.0 on 2025-12-24 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recipes', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha de consumo')),
                ('target_servings', models.PositiveIntegerField(default=4, verbose_name='Raciones para este día')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='users.planninggroup')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.meal')),
            ],
            options={
                'verbose_name': 'Plan Diario',
                'verbose_name_plural': 'Planes Diarios',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='ShoppingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.planninggroup')),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.FloatField(default=0)),
                ('unit', models.CharField(max_length=20)),
                ('is_purchased', models.BooleanField(default=False)),
                ('shopping_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='planner.shoppinglist')),
            ],
        ),
    ]
