# Generated by Django 6.0 on 2026-01-01 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
        ('recipes', '0004_alter_meal_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyplan',
            name='custom_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='dailyplan',
            name='is_eating_out',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dailyplan',
            name='meal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recipes.meal'),
        ),
    ]
