# Generated by Django 6.0 on 2025-12-25 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyplan',
            options={'ordering': ['date', 'meal_slot']},
        ),
        migrations.AddField(
            model_name='dailyplan',
            name='meal_slot',
            field=models.CharField(choices=[('BREAKFAST', 'Desayuno'), ('LUNCH', 'Comida'), ('DINNER', 'Cena'), ('SNACK', 'Otros')], default='LUNCH', max_length=20, verbose_name='Franja horaria'),
        ),
    ]
